# Generated by Django 4.2 on 2025-12-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название упражнения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок выполнения')),
                ('sets', models.PositiveIntegerField(default=1, verbose_name='Подходы')),
                ('repetitions', models.CharField(blank=True, max_length=100, verbose_name='Повторения/время')),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Отдых (сек)')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'упражнения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проведения')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин.)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки и комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='users.traininggroup', verbose_name='Группа')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='users.trainingtype', verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'тренировка',
                'verbose_name_plural': 'тренировки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('completed_sets', models.PositiveIntegerField(blank=True, null=True, verbose_name='Выполнено подходов')),
                ('actual_repetitions', models.CharField(blank=True, max_length=100, verbose_name='Факт. повторения')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вес (кг)')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='training.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'лог прогресса',
                'verbose_name_plural': 'логи прогресса',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.training', verbose_name='Тренировка'),
        ),
    ]
