# Generated by Django 4.2 on 2025-12-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_path, verbose_name='Аватар')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'тренер',
                'verbose_name_plural': 'тренеры',
            },
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная группа')),
            ],
            options={
                'verbose_name': 'тренировочная группа',
                'verbose_name_plural': 'тренировочные группы',
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'тип тренировки',
                'verbose_name_plural': 'типы тренировок',
            },
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_path, verbose_name='Аватар')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('razryad', models.CharField(blank=True, max_length=128, null=True, verbose_name='Разряд')),
                ('main_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sportsmen', to='users.trainer', verbose_name='Основной тренер')),
                ('training_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.traininggroup', verbose_name='Тренировочная группа')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'спортсмен',
                'verbose_name_plural': 'спортсмены',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('finish_time', models.DateTimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('type', models.CharField(choices=[('individual', 'Индивидуальная'), ('group', 'Групповая')], max_length=20, verbose_name='Тип занятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.traininggroup', verbose_name='Группа')),
                ('sportsman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sportsman', verbose_name='Спортсмен')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainer', verbose_name='Тренер')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainingtype', verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписания',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает ответа'), ('accepted', 'Принял'), ('declined', 'Отклонил')], default='waiting', max_length=20, verbose_name='Статус')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.schedule', verbose_name='Тренировка')),
                ('sportsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.sportsman', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'ответ спортсмена',
                'verbose_name_plural': 'ответы спортсменов',
                'unique_together': {('schedule', 'sportsman')},
            },
        ),
        migrations.CreateModel(
            name='TrainerTrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainer', verbose_name='Тренер')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainingtype', verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'тип тренировки тренера',
                'verbose_name_plural': 'типы тренировок тренеров',
                'unique_together': {('trainer', 'training_type')},
            },
        ),
    ]
